#!/bin/sh

export LC_COLLATE=zh_CN.UTF8

# set wmname
wmname LG3D

export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
export XMODIFIERS="@im=fcitx"
systemctl start --user fcitx
# fcitx-qimpanel &

hsetroot -solid '#000000' &
compton -b

# xscreensaver -nosplash &

# unlock keyring
eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
export SSH_AUTH_SOCK

# start clipboard
clipit &
# parcellite &

# bluetooth
# blueman-applet &

# transmission
# transmission-gtk -m &

# shutter
shutter --min_at_startup &

# automount
# pkttyagent &
# udiskie -As &
# devmon &
pcmanfm -d &

# conky
start-conky &

# vim
mkdir -p /tmp/vim_undodir

# start terminal at autostart
urxvtc

# start pulseaudio and system tray for it
start-pulseaudio-x11
pasystray &

# aria2
aria2c -D

# cache dmenu
#dmenu_path > /dev/null
